package com.speednet.module.subscription.service;

import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;
import java.net.URI;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Converts only client-side connection URIs generated by SubscriptionConnection. */
public final class ClashSubscription {
    private ClashSubscription() {}
    private static String decode(String value) { return URLDecoder.decode(value, StandardCharsets.UTF_8); }
    private static String text(Map<String,Object> map, String key, String fallback) {
        Object value = map.get(key); return value == null ? fallback : value.toString();
    }
    public static Map<String,Object> proxy(String link) {
        var p = new LinkedHashMap<String,Object>();
        String network, security, path, host, sni;
        Map<String,Object> params;
        if (link.startsWith("vmess://")) {
            params = SubscriptionConnection.object(new String(Base64.getDecoder().decode(link.substring(8)), StandardCharsets.UTF_8));
            p.put("name", text(params,"ps","节点")); p.put("type","vmess");
            p.put("server",text(params,"add","")); p.put("port",Integer.parseInt(text(params,"port","0")));
            p.put("uuid",text(params,"id","")); p.put("alterId",Integer.parseInt(text(params,"aid","0")));
            p.put("cipher",text(params,"scy","auto"));
            network=text(params,"net","tcp"); security=text(params,"tls","");
            path=text(params,"path",""); host=text(params,"host",""); sni=text(params,"sni","");
        } else {
            var uri=URI.create(link); String protocol=uri.getScheme();
            if (!Set.of("vless","trojan").contains(protocol)) throw new IllegalArgumentException("不支持的 Clash 节点协议");
            params=new LinkedHashMap<>();
            if(uri.getRawQuery()!=null) for(String part:uri.getRawQuery().split("&")) {
                var pair=part.split("=",2); params.put(decode(pair[0]),pair.length==2?decode(pair[1]):"");
            }
            p.put("name",uri.getRawFragment()==null?"节点":decode(uri.getRawFragment())); p.put("type",protocol);
            p.put("server",uri.getHost()==null?"":uri.getHost().replaceAll("^\\[|\\]$",""));p.put("port",uri.getPort());
            if(uri.getRawUserInfo()==null)throw new IllegalArgumentException("节点凭据缺失");
            p.put("trojan".equals(protocol)?"password":"uuid",decode(uri.getRawUserInfo()));
            network=text(params,"type","tcp");security=text(params,"security","none");
            path=text(params,"grpc".equals(network)?"serviceName":"path","");host=text(params,"host","");sni=text(params,"sni","");
        }
        if (!Set.of("tcp","ws","grpc").contains(network) || !Set.of("","none","tls").contains(security))
            throw new IllegalArgumentException("该节点传输或安全类型暂不支持 Clash 订阅");
        if (text(p,"server","").isBlank() || (int)p.get("port")<1 || (int)p.get("port")>65535)
            throw new IllegalArgumentException("节点地址或端口无效");
        p.put("udp",true);
        if ("tls".equals(security)) {
            if(!"trojan".equals(p.get("type")))p.put("tls",true);
            if(!sni.isBlank())p.put("trojan".equals(p.get("type"))?"sni":"servername",sni);
            if(!text(params,"alpn","").isBlank())p.put("alpn",List.of(text(params,"alpn","").split(",")));
        } else if ("trojan".equals(p.get("type"))) {
            throw new IllegalArgumentException("Clash Trojan 节点需要 TLS，请调整入站安全配置");
        }
        if (!"tcp".equals(network))p.put("network",network);
        if ("ws".equals(network)) {
            var options=new LinkedHashMap<String,Object>(); options.put("path",path.isBlank()?"/":path);
            if(!host.isBlank())options.put("headers",Map.of("Host",host));p.put("ws-opts",options);
        }
        if ("grpc".equals(network))p.put("grpc-opts",Map.of("grpc-service-name",path));
        return p;
    }
    public static String render(List<String> links) { return render(links,ClashRuleService.DEFAULT_RULES); }
    public static String render(List<String> links,List<String> rules) {
        if(links.isEmpty())throw new IllegalArgumentException("订阅暂无可用节点");
        var proxies=new ArrayList<Map<String,Object>>();var names=new HashSet<String>();
        names.add("DIRECT");names.add("REJECT");names.add("SpeedNet");
        for(String link:links){var p=proxy(link);String base=text(p,"name","节点");if(base.isBlank())base="节点";
            String name=base;int suffix=2;while(!names.add(name))name=base+" ("+suffix+++")";
            p.put("name",name);proxies.add(p);
        }
        var config=new LinkedHashMap<String,Object>();config.put("mixed-port",7890);config.put("allow-lan",false);
        config.put("mode","rule");config.put("log-level","info");config.put("proxies",proxies);
        var selection=new ArrayList<String>();for(var p:proxies)selection.add(p.get("name").toString());selection.add("DIRECT");
        config.put("proxy-groups",List.of(Map.of("name","SpeedNet","type","select","proxies",selection)));
        config.put("rules",ClashRuleService.validate(rules));
        var options=new DumperOptions();options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);options.setAllowUnicode(true);
        return new Yaml(options).dump(config);
    }
}
