package com.speednet.module.subscription.service;
import com.speednet.module.subscription.dal.dataobject.SubscriptionDO;
import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;
class SubscriptionPolicyTest {
 final LocalDateTime now=LocalDateTime.of(2026,10,1,12,0);
 SubscriptionDO subscription(){return new SubscriptionDO().setStartTime(now.minusDays(1)).setExpiryTime(now.plusDays(30)).setPaused(false).setUnlimited(false).setTotalBytes(1000L).setUsedUpload(100L).setUsedDownload(200L).setTrafficMode("both").setResetMode("none").setResetIntervalDays(30);}
 @Test void statusesHaveExplicitPrecedence(){var s=subscription();assertEquals(1,SubscriptionPolicy.status(s,now));s.setStartTime(now.plusDays(1));assertEquals(0,SubscriptionPolicy.status(s,now));s.setPaused(true);assertEquals(2,SubscriptionPolicy.status(s,now));s.setExpiryTime(now);assertEquals(4,SubscriptionPolicy.status(s,now));s.setEndedTime(now.minusHours(1));assertEquals(5,SubscriptionPolicy.status(s,now));}
 @Test void quotaSupportsDownloadOnlyAndUnlimited(){var s=subscription().setUsedUpload(900L);assertEquals(3,SubscriptionPolicy.status(s,now));s.setTrafficMode("download");assertEquals(200,SubscriptionPolicy.used(s));assertEquals(1,SubscriptionPolicy.status(s,now));s.setUnlimited(true).setUsedDownload(10000L);assertEquals(1,SubscriptionPolicy.status(s,now));}
 @Test void trafficSamplesAreIdempotentAndHandleRemoteCounterReset(){assertEquals(40,SubscriptionPolicy.delta(100,140));assertEquals(0,SubscriptionPolicy.delta(140,140));assertEquals(8,SubscriptionPolicy.delta(140,8));assertThrows(IllegalArgumentException.class,()->SubscriptionPolicy.delta(0,-1));}
 @Test void extensionUsesExistingExpiryOrCurrentTime(){var s=subscription();assertEquals(s.getExpiryTime().plusDays(7),SubscriptionPolicy.extend(s,7,null,now));s.setExpiryTime(now.minusDays(2));assertEquals(now.plusDays(7),SubscriptionPolicy.extend(s,7,null,now));assertThrows(IllegalArgumentException.class,()->SubscriptionPolicy.extend(s,null,now.minusDays(1),now));}
 @Test void automaticResetsAreExplicit(){var s=subscription();assertNull(SubscriptionPolicy.nextReset(s,now));s.setResetMode("monthly");assertEquals(now.plusMonths(1),SubscriptionPolicy.nextReset(s,now));s.setResetMode("interval").setResetIntervalDays(7);assertEquals(now.plusDays(7),SubscriptionPolicy.nextReset(s,now));}
 @Test void apiDatesUseExistingEpochMillisContract(){long start=now.atZone(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli();String json="{\"startTime\":"+start+",\"expiryTime\":"+(start+86400000)+"}";var req=com.speednet.framework.common.util.json.JsonUtils.parseObject(json,com.speednet.module.subscription.controller.admin.vo.SubscriptionCreateReqVO.class);assertEquals(now,req.getStartTime());assertEquals(now.plusDays(1),req.getExpiryTime());}
 @Test void tokensAreRandomAndHashesAreStable(){String a=SubscriptionPolicy.token(),b=SubscriptionPolicy.token();assertEquals(43,a.length());assertNotEquals(a,b);assertEquals(64,SubscriptionPolicy.hash(a).length());assertEquals(SubscriptionPolicy.hash(a),SubscriptionPolicy.hash(a));assertNotEquals(SubscriptionPolicy.hash(a),SubscriptionPolicy.hash(b));}
}
