<template><Dialog v-model="visible" :title="title"><el-form ref="formRef" :model="form" :rules="rules" label-width="110px" v-loading="loading">
 <el-form-item label="服务器名称" prop="name"><el-input v-model="form.name" /></el-form-item>
 <el-form-item label="主机/IP" prop="host"><el-input v-model="form.host" /></el-form-item>
 <el-row :gutter="16"><el-col :span="12"><el-form-item label="SSH 端口" prop="sshPort"><el-input-number v-model="form.sshPort" :min="1" :max="65535" /></el-form-item></el-col><el-col :span="12"><el-form-item label="SSH 用户" prop="sshUsername"><el-input v-model="form.sshUsername" /></el-form-item></el-col></el-row>
 <el-form-item label="认证方式"><el-radio-group v-model="form.sshAuthType"><el-radio :value="1">密码</el-radio><el-radio :value="2">私钥</el-radio></el-radio-group></el-form-item>
 <el-form-item v-if="form.sshAuthType===1" label="SSH 密码"><el-input v-model="form.sshPassword" type="password" show-password :placeholder="form.id?'留空表示不修改':''" /></el-form-item>
 <template v-else><el-form-item label="SSH 私钥"><el-input v-model="form.sshPrivateKey" type="textarea" :rows="5" :placeholder="form.id?'留空表示不修改':'粘贴 PEM/OpenSSH 私钥'" /></el-form-item><el-form-item label="私钥口令"><el-input v-model="form.sshKeyPassphrase" type="password" show-password /></el-form-item></template>
 <el-divider content-position="left">已有面板信息（可选）</el-divider><el-row :gutter="16"><el-col :span="8"><el-form-item label="协议"><el-select v-model="form.panelScheme"><el-option label="HTTPS" value="https"/><el-option label="HTTP" value="http"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="面板端口"><el-input-number v-model="form.panelPort" :min="1" :max="65535" /></el-form-item></el-col></el-row>
 <el-form-item label="面板路径"><el-input v-model="form.panelPath" /></el-form-item><el-form-item label="API Token"><el-input v-model="form.panelToken" type="password" show-password :placeholder="form.id?'留空表示不修改':''" /></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" /></el-form-item>
</el-form><template #footer><el-button @click="submit" type="primary" :disabled="loading">确定</el-button><el-button @click="visible=false">取消</el-button></template></Dialog></template>
<script setup lang="ts">import * as Api from '@/api/xray/server';const emit=defineEmits(['success']);const visible=ref(false),loading=ref(false),formRef=ref();const title=ref('');const empty=()=>({id:undefined,name:'',host:'',sshPort:22,sshUsername:'root',sshAuthType:1,sshPassword:'',sshPrivateKey:'',sshKeyPassphrase:'',panelScheme:'https',panelPort:undefined,panelPath:'',panelToken:'',remark:''});const form=ref<any>(empty());const rules={name:[{required:true,message:'请输入服务器名称'}],host:[{required:true,message:'请输入主机或 IP'}],sshUsername:[{required:true,message:'请输入 SSH 用户名'}]};const open=async(type:string,id?:number)=>{visible.value=true;title.value=type==='create'?'新增服务器':'编辑服务器';form.value=empty();if(id){loading.value=true;try{form.value={...form.value,...await Api.getServer(id)}}finally{loading.value=false}}};defineExpose({open});const submit=async()=>{await formRef.value.validate();loading.value=true;try{form.value.id?await Api.updateServer(form.value):await Api.createServer(form.value);useMessage().success('保存成功');visible.value=false;emit('success')}finally{loading.value=false}};</script>
