package com.speednet.custom.auth;

import com.speednet.custom.auth.AuthDtos.LoginRequest;
import com.speednet.custom.auth.AuthDtos.RegisterRequest;
import com.speednet.custom.common.ApiException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:custom_auth;MODE=MySQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.username=sa", "spring.datasource.password=",
        "spring.flyway.enabled=false", "custom.tenant-id=1"
})
class AuthServiceTest {
    @Autowired AuthService auth;
    @Autowired JdbcTemplate jdbc;

    @BeforeEach
    void setup() {
        jdbc.execute("CREATE TABLE IF NOT EXISTS member_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id BIGINT,email VARCHAR(128),password VARCHAR(100),status INT,register_ip VARCHAR(64),register_terminal INT,nickname VARCHAR(64),avatar VARCHAR(100),point INT,experience INT,deleted BOOLEAN DEFAULT FALSE,login_ip VARCHAR(64),login_date TIMESTAMP)");
        jdbc.execute("CREATE UNIQUE INDEX IF NOT EXISTS uk_member_email ON member_user(tenant_id,email)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS custom_email_code (tenant_id BIGINT,email VARCHAR(128),code_hash VARCHAR(100),expires_at TIMESTAMP,last_sent_at TIMESTAMP,attempts INT,consumed BOOLEAN,PRIMARY KEY(tenant_id,email))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS custom_session (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id BIGINT,member_user_id BIGINT,access_hash CHAR(64),refresh_hash CHAR(64),access_expires_at TIMESTAMP,refresh_expires_at TIMESTAMP,revoked BOOLEAN DEFAULT FALSE,create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.update("DELETE FROM custom_session");
        jdbc.update("DELETE FROM custom_email_code");
        jdbc.update("DELETE FROM member_user");
    }

    @Test
    void registrationLoginAndAdminDisable() {
        String code = auth.sendCode("  USER@Example.com  ");
        assertNotNull(code);
        var session = auth.register(new RegisterRequest("USER@Example.com", code, "secret1234"), "127.0.0.1");
        assertEquals("user@example.com", session.member().email());
        assertEquals(session.member().id(), auth.authenticate(session.accessToken()));
        var refreshed = auth.refresh(session.refreshToken());
        assertThrows(ApiException.class, () -> auth.authenticate(session.accessToken()));
        assertEquals(session.member().id(), auth.authenticate(refreshed.accessToken()));
        assertEquals(session.member().id(), auth.login(new LoginRequest("USER@Example.com", "secret1234"), "127.0.0.1").member().id());
        jdbc.update("UPDATE member_user SET status=1 WHERE id=?", session.member().id());
        assertThrows(ApiException.class, () -> auth.authenticate(refreshed.accessToken()));
        assertThrows(ApiException.class, () -> auth.login(new LoginRequest("USER@Example.com", "secret1234"), "127.0.0.1"));
    }
}
